// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Resume.Data;

#nullable disable

namespace Resume.Data.Migrations
{
    [DbContext(typeof(ResumeContext))]
    [Migration("20250421184112_WithResumeFile3")]
    partial class WithResumeFile3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Resume.Core.Models.Match", b =>
                {
                    b.Property<int>("MatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchID"));

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResumefileID1")
                        .HasColumnType("int");

                    b.Property<int>("ResumefileID2")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MatchID");

                    b.HasIndex("ResumefileID1");

                    b.HasIndex("ResumefileID2");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Resume.Core.Models.ResumeFile", b =>
                {
                    b.Property<int>("ResumeFileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResumeFileID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResumeFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ResumeFileID");

                    b.HasIndex("UserID");

                    b.ToTable("ResumeFiles");
                });

            modelBuilder.Entity("Resume.Core.Models.Sharing", b =>
                {
                    b.Property<int>("ShareID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShareID"));

                    b.Property<int>("ResumefileID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SharedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SharedWithUserID")
                        .HasColumnType("int");

                    b.HasKey("ShareID");

                    b.HasIndex("ResumefileID");

                    b.ToTable("Sharings");
                });

            modelBuilder.Entity("Resume.Core.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SharingShareID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("SharingShareID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Resume.Core.Models.Match", b =>
                {
                    b.HasOne("Resume.Core.Models.ResumeFile", "Resumefile1")
                        .WithMany()
                        .HasForeignKey("ResumefileID1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Resume.Core.Models.ResumeFile", "Resumefile2")
                        .WithMany()
                        .HasForeignKey("ResumefileID2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resumefile1");

                    b.Navigation("Resumefile2");
                });

            modelBuilder.Entity("Resume.Core.Models.ResumeFile", b =>
                {
                    b.HasOne("Resume.Core.Models.User", null)
                        .WithMany("Files")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("Resume.Core.Models.Sharing", b =>
                {
                    b.HasOne("Resume.Core.Models.ResumeFile", "Resumefile")
                        .WithMany()
                        .HasForeignKey("ResumefileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resumefile");
                });

            modelBuilder.Entity("Resume.Core.Models.User", b =>
                {
                    b.HasOne("Resume.Core.Models.Sharing", null)
                        .WithMany("SharedWithUser")
                        .HasForeignKey("SharingShareID");
                });

            modelBuilder.Entity("Resume.Core.Models.Sharing", b =>
                {
                    b.Navigation("SharedWithUser");
                });

            modelBuilder.Entity("Resume.Core.Models.User", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
